livraria/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home
# Renomeado para uma nomenclatura mais genérica
# from pagamento import urls as pagamento_urls

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    path('cliente/', include('cliente.urls', namespace='cliente')),
    path('livro/', include('livro.urls', namespace='livro')),
    path('pedido/', include('pedidos.urls', namespace='pedidos')),
    path('pagamento/', include('pagamento.urls', namespace='pagamento')),
    path('paypal', include('paypal.standard.ipn.urls')),

]

livro/urls.py
from django.urls import path
from .views import listar_livros, detalhe_livro, search_view
from . import views
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Livros'

urlpatterns = [
    path('', views.listar_livros),
    path('detalhe_livro/<int:id>/', views.detalhe_livro),
    path('adicionar-ao-carrinho/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('search/', views.search_view, name='search'),
]

if settings.DEBUG: urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

livro/models.py
from django.db import models

class Editora(models.Model):
    nome = models.CharField(max_length=150)
    cnpj = models.IntegerField()

class Genero(models.Model):
    class Meta:
        verbose_name_plural = 'Generos'

    nome = models.CharField(max_length=150)

    def __str__(self):
        return self.nome

class Autores(models.Model):
    class Meta:
        verbose_name_plural = 'Autores'

    nome = models.CharField(max_length=150)
    sobrenome = models.CharField(max_length=150)

    def __str__(self):
        return self.nome


class Livro(models.Model):
    isbn = models.IntegerField()
    titulo = models.CharField(max_length=150)
    valor = models.FloatField()
    estoque = models.IntegerField()
    descricao = models.CharField(max_length=200)
    editora = models.ForeignKey(Editora, on_delete=models.DO_NOTHING)
    id_genero = models.ForeignKey(Genero, on_delete=models.DO_NOTHING)
    autores = models.ManyToManyField(Autores)
    imagem_capa = models.ImageField(upload_to='img/livros/capas', null=True, blank=True)

    
class Livros(models.Model):
 imagem = models.ImageField(upload_to="{% static 'static\img\capas' %}")


# class Pedidos(models.Model):
#     class Meta:
#         verbose_name_plural = 'Pedidos'

#     STATUS_CHOICES = [
#         ('PENDENTE', 'Pendente'),
#         ('EM_PROCESSAMENTO', 'Em Processamento'),
#         ('CONCLUIDO', 'Concluído'),
#         ('CANCELADO', 'Cancelado'),
#     ]
#     data = models.DateTimeField()
#     status = models.CharField(max_length=20, choices=STATUS_CHOICES)
#     usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

livro/forms.py
from django import forms
from .models import Livro, Genero, Autores

class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        generos = Genero.objects.all()
        autores = Autores.objects.all()
        self.fields['id_genero'].queryset = generos
        self.fields['autores'].queryset = autores

livro/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import LivroForm
from .models import Livro
from pedidos.models import Carrinho


def listar_livros(request):
    livros = Livro.objects.all()
    contexto = {
        'livros': livros,
    }
    return render(request, 'lista_livros.html', contexto)


def detalhe_livro(request, id=None):
    try:
        instance = get_object_or_404(Livro, id=id)
    except Http404:
        messages.error(request, f'Livro com id={id} não localizado')
        return redirect('/livro/')

    form_livro = LivroForm(request.GET)
    context = {
        'livro': instance,
        'form_livro': form_livro,
    }
    return render(request, "detalhe_livro.html", context)


@login_required
def adicionar_ao_carrinho(request):
    if request.user.is_authenticated:
        livro_id = request.POST.get('livro_id')
        quantidade = int(request.POST.get('quantidade'))
        cliente = request.user
        carrinho = Carrinho()
        msg_retorno = carrinho.add_item_carrinho(
            cliente_id=cliente.id, livro_id=livro_id, quantidade=quantidade)

        if msg_retorno == True:
            messages.success(request, 'Livro adicionado ao carrinho')
        else:
            messages.error(request, msg_retorno)

        return redirect(f'/livro/detalhe_livro/{livro_id}')
    else:
        return redirect('/')


def search_view(request):
    query = request.GET.get('q')
    results = None

    if query:
        results = Livro.objects.filter(titulo__icontains=query)

    return render(request, 'search_results.html', {'query': query, 'results': results})

livro/templates/detalhe_livro.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_messages %}

<!doctype html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Womakers Lib</title>

    <!-- Links do bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- link dos ícones do bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <!-- link do estilo css -->
    <link rel="stylesheet" type="text/css" href="{% static 'estilo.css'%}">

    <!-- links das fontes da tipografia -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">
</head>

<body>

    <!-- header da página -->
    <header class="container">
        <div class="row align-items-center">
            <a class="col-2" href="/">
                <img class="img-fluid" src="{% static './assets/img/logo.png' %}" alt="" width="197" height="137">
            </a>
            <div class="col-8 row">
                <div class="input-group flex-nowrap">
                    <form class="search-container justify-content-center" action="{% url 'Livros:search' %}" method="get">
                        <input class="search-input form-control" autocomplete="off" type="search" name="q" placeholder="O que você está buscando?">
                        <button type="submit" class="btn search-input-submit" value="Buscar" aria-label="Buscar">
                            <i class="bi bi-search justify-left"></i>
                        </button>
                    </form>
                </div>
            </div>
            <!-- navbar do menu de botões do header -->
            <nav class="col-2 nav justify-content-center">
                <!-- botão de perfil do usuário -->
                <a class="nav-link active" aria-current="page" href="/cliente/perfil/">
                    <img src="{% static './assets/svg/profile.svg' %}" alt="" width="46" height="46">
                </a>
                <!-- botão do carrinho -->
                <a class="nav-link" href="/pedido/detalhes_carrinho/">
                    <img src="{% static './assets/svg/cart.svg' %}" alt="" width="46" height="46">
                </a>
            </nav>
        </div>
    </header>
    <!-- separador está fora do header pois a classe container limita a largura do elemento, e ele precisava ocupar a largura total da página de acordo com o design-->
    <span class="separator">
        Categorias
    </span>

    <!-- conteúdo principal -->
    <main>
        <section class="container">
            <!-- Parte de compra -->
            <div class="row ">
                <!-- Div que contém a imagem do livro-->
                <div class="col-4">
                    <img class="img-fluid" src="{% static 'media/' %}{{ livro.imagem_capa }}" alt="{{ livro.titulo }}" width="335" height="509">
                </div>
                <!-- informações do livro -->
                <div class="col">
                    <h2 class="book-title">{{ livro.titulo }}</h2>
                    <span class="info">
                        <h4>Autor:
                            {% for autor in livro.autores.all %}
                            {{ autor.nome }} {{ autor.sobrenome }}
                            {% endfor %}</h4>
                    </span>
                    <span class="info">
                        <h4>Editora: {{ livro.editora.nome }}
                    </span>
                    <span class="info">
                        <h4> {{ livro.valor }} </h4>
                    </span>
                    <!-- Botões de compra e quantidade de itens -->
                    <form method="POST" action="/livro/adicionar-ao-carrinho/">
                        {% csrf_token %}
                        <div class="btns">
                            <!-- botão de quantidade -->
                            <input type="number" name="quantidade" min="1" max="99" value="1">
                            <input type="hidden" name="livro_id" value="{{ livro.id }}">
                            <!-- botão de compra -->
                            <button type="submit" class="buy-btn" data-action="add">
                                Adicionar ao Carrinho
                                <i class="bi bi-cart3"></i>
                            </button>
                        </div>
                    </form>
                    <!-- Calculo de frete -->
                    <div class="frete">
                        <p>Calcule o frete</p>
                        <input type="text">
                        <button>Ok</button>
                    </div>
                </div>
            </div>
            <!-- parte de descrição do livro -->
            <div class="row justify-content-center sinopse">
                <p> {{ livro.descricao }} </p>
            </div>
            <!-- parte da ficha técnica do livro -->
            <div class="row justify-content-center datasheet">
                <h1>Ficha Tecnica</h1>
                <div>
                    <table class="table">
                        <tbody>
                            <tr>
                                <th scope="row">Editora</th>
                                <td> {{ livro.editora.nome }} </td>
                            </tr>
                            <tr>
                                <th scope="row">ISBN</th>
                                <td>{{ livro.isbn }} </td>
                            </tr>
                            <tr>
                                <th scope="row">Gênero</th>
                                <td>{{ livro.id_genero.nome }} </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </main>
    <!-- Rodapé -->
    <footer class="container">
        <section class="row">
            <!-- Parte de pagamentos -->
            <div class="col-6 payments">
                <p>Pague com</p>
                <div>
                    <img src="{% static './assets/img/forma-pagamento-1.png' %}" alt="" width="89" height="58">
                    <img src="{% static './assets/img/forma-pagamento-2.png' %}" alt="" width="89" height="58">
                    <img src="{% static './assets/img/forma-pagamento-3.png' %}" alt="" width="89" height="58">
                </div>
            </div>
            <!-- Parte de redes sociais -->
            <div class="col-6 socials">
                <p>Nos siga nas redes</p>
                <nav class="nav justify-content-center">
                    <a class="nav-link active" aria-current="page" href="#">
                        <img src="{% static './assets/svg/twitter.svg' %}" alt="" width="26" height="26">
                    </a>
                    <a class="nav-link" href="#">
                        <img src="{% static './assets/svg/facebook.svg' %}" alt="" width="26" height="26">
                    </a>
                    <a class="nav-link" href="#">
                        <img src="{% static './assets/svg/linkedin.svg' %}" alt="" width="26" height="26">
                    </a>
                    <a class="nav-link" href="#">
                        <img src="{% static './assets/svg/instagram.svg' %}" alt="" width="26" height="26">
                    </a>
                </nav>
            </div>
        </section>
    </footer>

    <!-- Outro separador -->
    <span class="separator"></span>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static './js/add_to_car.js' %}"></script> -->

</body>

</html>

livro/templates/lista_livros.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">   
  
    <!-- fontes-->     
      <link href="https://fonts.googleapis.com/css?family=Titillium+Web&display=swap" rel="stylesheet" />
      <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet" />
      <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
        
    <title>WoMakersLib</title>
    <!-- Bootstrap CSS -->
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <!-- importar css-->
    <base href="/">
    <link rel="stylesheet" href="{% static 'style.css' %}"> 
  </head>
    
  <body>
    <header class="container">
      <div class="row align-items-center">
        <a class="col-2" href="/">
          <div class="logo-img-container">
            <img src="{% static 'assets\img\logo.png' %}" alt="Womakers Lib" class="logo-img transition-soft align-self-center" width="190" height="130">
          </div>
        </a>
        <div class="col-8 row">
          <div class="input-group flex-nowrap">
            <form class="search-container justify-content-center" action="{% url 'Livros:search' %}" method="get">
              <input class="search-input form-control" autocomplete="off" type="search" name="q" placeholder="O que você está buscando?">
              <button type="submit" class="btn search-input-submit" value="Buscar" aria-label="Buscar">
                  <i class="bi bi-search justify-left"></i>
              </button>
          </form>          
          </div>
        </div>
        <nav class="col-2 nav justify-content-center">
          <a class="nav-link active" aria-current="page" href="/cliente/perfil/">
            <img src="{% static './assets/svg/profile.svg' %}" alt="" width="46" height="46">
          </a>
          <a class="nav-link" href="/pedido/detalhes_carrinho/">
            <img src="{% static './assets/svg/cart.svg' %}" alt="" width="46" height="46">
          </a>
        </nav>
      </div>
    </header>

  <span class="separator">
    Categorias
  </span>
    
    <!-- Lista de livros -->
    <main>
      <div class="row g-0">
        {% for livro in livros %}
          <div class="col-md-3 mb-4">
            <div class="card mb-3" style="max-width: 540px;">
              <div class="d-flex flex-row">
                {% if livro.imagem_capa %}
                  <img src="{% static 'media/' %}{{ livro.imagem_capa }}" class="img-fluid rounded-start align-self-center" alt="{{ livro.titulo }}" width="150" height="150">
                {% else %}
                  <img src="{% static 'media/unavailable.jpg' %}" alt="Image unavailable" class="img-fluid mb-3" width="26">
                {% endif %}
    
                <div class="card-body d-flex flex-column align-items-start">
                  <div class="ml-3">
                    <h5 class="card-title">{{ livro.titulo }}</h5>
                    <p class="card-text">
                      Autor(es):
                      {% for autor in livro.autores.all %}
                        {{ autor.nome }} {{ autor.sobrenome }}
                      {% endfor %}
                    </p>
                    <p class="card-text">
                      Preço: {{ livro.valor }}
                    </p>
                    <a href="/livro/detalhe_livro/{{livro.id}}" class="btn-livros btn-primary">Ver Mais</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </main>
    

  
 

    <footer class="container">
        <section class="row">
            <div class="col-6 payments">
                <p>Pague com</p>
                <div>
                    <img src="{% static './assets/img/forma-pagamento-1.png' %}" alt="" width="89" height="58">
                    <img src="{% static './assets/img/forma-pagamento-2.png' %}" alt="" width="89" height="58">
                    <img src="{% static './assets/img/forma-pagamento-3.png' %}" alt="" width="89" height="58">
                </div>          
            </div>
            <div class="col-6 socials">
                <p>Nos siga nas redes</p>
                <nav class="nav justify-content-center">
                    <a class="nav-link active" aria-current="page" href="#">
                        <img src="{% static './assets/svg/twitter.svg' %}" alt="" width="26" height="26">
                    </a>
                    <a class="nav-link" href="#">
                        <img src="{% static './assets/svg/facebook.svg' %}" alt="" width="26" height="26">
                    </a>
                    <a class="nav-link" href="#">
                        <img src="{% static './assets/svg/linkedin.svg' %}" alt="" width="26" height="26">
                    </a>
                    <a class="nav-link" href="#">
                        <img src="{% static './assets/svg/instagram.svg' %}" alt="" width="26" height="26">
                    </a>
                </nav>
            </div>
        </section>
    </footer>

    <span class="separator">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
      Copyright Womakers 2024. Todos os direitos reservados.
    </span>  </body>
</html

livro/templates/search_results.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Resultado da busca</title>

  <!-- Links do bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <!-- link dos ícones do bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

  <!-- link do estilo css -->
  <link rel="stylesheet" type="text/css" href="{% static 'estilo.css'%}">

  <!-- links das fontes da tipografia -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">
</head>

<body>
  <header class="container">
    <div class="row align-items-center">
      <a class="col-2" href="/">
        <img class="img-fluid" src="{% static './assets/img/logo.png' %}" alt="" width="197" height="137">
      </a>
      <div class="col-8 row">
        <div class="input-group flex-nowrap">
          <form class="search-container justify-content-center" action="/livro/search/" method="get">
            <input class="search-input form-control" autocomplete="off" type="search" name="q" placeholder="O que você está buscando?">
            <button type="submit" class="btn search-input-submit" value="Buscar" aria-label="Buscar">
                <i class="bi bi-search justify-left"></i>
            </button>
        </form>          
        </div>
      </div>
      <!-- navbar do menu de botões do header -->
      <nav class="col-2 nav justify-content-center">
        <!-- botão de perfil do usuário -->
        <a class="nav-link active" aria-current="page" href="/cliente/perfil/">
          <img src="{% static './assets/svg/profile.svg' %}" alt="" width="46" height="46">
        </a>
        <!-- botão do carrinho -->
        <a class="nav-link" href="/pedido/carrinho/">
          <img src="{% static './assets/svg/cart.svg' %}" alt="" width="46" height="46">
        </a>
      </nav>
    </div>
  </header>

  <span class="separator">
    Categorias
  </span>

  <main>
    <section class="container">
      <div class="row align-items-center">
        {% if query %}
        <h2>Resultados da busca por "{{ query }}"</h2>
        {% if results %}
        {% for livro in results %}
        <div class="col-4">
          <img class="img-fluid" src="{% static 'media/' %}{{ livro.imagem_capa }}" alt="{{ livro.titulo }}" width="335" height="509">
        </div>
        <div class="col">
          <a href="/livro/detalhe_livro/{{ livro.id }}/" class="botaozin">VER LIVRO</a>
        </div>
        {% endfor %}
        {% else %}
        <p>Nenhum resultado encontrado.</p>
        {% endif %}
        {% endif %}
      </div>
    </section>
  </main>
</body>

</html>